In [ ]:
import pandas as pd

players = pd.read_csv("../data/2024-2025/players/players.csv")
matches = pd.read_csv("../data/2024-2025/matches/matches.csv")
playermatch = pd.read_csv("../data/2024-2025/playermatchstats/playermatchstats.csv")

players.head()
matches[['match_id','gameweek','kickoff_time','home_team_elo','away_team_elo']].head()
playermatch.columns.tolist()

['player_id',
 'match_id',
 'minutes_played',
 'goals',
 'assists',
 'total_shots',
 'xg',
 'xa',
 'xgot',
 'shots_on_target',
 'successful_dribbles',
 'big_chances_missed',
 'touches_opposition_box',
 'touches',
 'accurate_passes',
 'chances_created',
 'final_third_passes',
 'accurate_crosses',
 'accurate_long_balls',
 'tackles_won',
 'interceptions',
 'recoveries',
 'blocks',
 'clearances',
 'headed_clearances',
 'dribbled_past',
 'duels_won',
 'duels_lost',
 'ground_duels_won',
 'aerial_duels_won',
 'was_fouled',
 'fouls_committed',
 'saves',
 'goals_conceded',
 'xgot_faced',
 'goals_prevented',
 'sweeper_actions',
 'gk_accurate_passes',
 'gk_accurate_long_balls',
 'offsides',
 'high_claim',
 'tackles',
 'accurate_passes_percent',
 'accurate_crosses_percent',
 'accurate_long_balls_percent',
 'ground_duels_won_percent',
 'aerial_duels_won_percent',
 'successful_dribbles_percent',
 'tackles_won_percent',
 'start_min',
 'finish_min',
 'team_goals_conceded',
 'penalties_scored',
 'penalties_missed']

In [10]:
# aggregate goals per player
goals = playermatch.groupby('player_id')['goals'].sum().reset_index()
goals = goals.merge(players[['player_id','first_name','second_name','web_name']], on='player_id', how='left')
goals.sort_values('goals', ascending=False).head(15)

     player_id  goals     first_name               second_name       web_name
253        328     29        Mohamed                     Salah        M.Salah
314        401     23      Alexander                      Isak           Isak
271        351     22         Erling                   Haaland        Haaland
344        447     20          Chris                      Wood           Wood
77          99     20          Bryan                    Mbeumo         Mbeumo
86         110     19          Yoane                     Wissa          Wissa
44          58     16          Ollie                   Watkins        Watkins
416        541     15        Matheus  Santos Carneiro Da Cunha          Cunha
132        182     15           Cole                    Palmer         Palmer
153        207     14  Jean-Philippe                    Mateta         Mateta
434        566     14         Jørgen             Strand Larsen  Strand Larsen
396        514     13         Jarrod                     Bowen          Bowen
252        327     13           Luis                      Díaz      Luis Díaz
190        252     12           Raúl                   Jiménez           Raúl
54          71     12         Justin                  Kluivert       Kluivert